version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sistema-moeda-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - sistema-moeda-network

  db:
    image: mysql:8.0
    container_name: sistema-moeda-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_moeda
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sistema-moeda-network

  backend:
    build: ./backend
    image: sistemamoeda-backend-test
    container_name: sistema-moeda-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sistema_moeda?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - sistema-moeda-network

volumes:
  db_data:

networks:
  sistema-moeda-network:
    driver: bridge
